# Generated by Django 3.0.4 on 2020-03-29 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vocabularies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('interpretation', models.TextField()),
                ('word_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocabularies.Vocab')),
            ],
        ),
    ]
