# Generated by Django 3.0.4 on 2020-04-12 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vocabularies', '0007_auto_20200412_0925'),
        ('word_logs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TestLog',
            new_name='WordLog',
        ),
        migrations.RenameField(
            model_name='wordlog',
            old_name='interpretation',
            new_name='log',
        ),
    ]
